/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DateTimePicker: typeof import('./components/DateTimePicker.vue')['default']
    H5AudioPanel: typeof import('./components/H5AudioPanel.vue')['default']
    MoodModal: typeof import('./components/MoodModal.vue')['default']
    SmsSettingsModal: typeof import('./components/SmsSettingsModal.vue')['default']
    TransferMoneyPanel: typeof import('./components/TransferMoneyPanel.vue')['default']
  }
}
